name: go vet

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*.go'
      - '.github/workflows/vet.yml'

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  vet:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run go vet
        run: ./tool/go vet ./...

      - name: Build checklocks
        run: ./tool/go build -o /tmp/checklocks gvisor.dev/gvisor/tools/checklocks/cmd/checklocks

      - name: Run checklocks vet
        # TODO: remove || true once we have applied checklocks annotations everywhere.
        run: ./tool/go vet -vettool=/tmp/checklocks ./... || true
